events {}

http {
    upstream ff_service {
        server ff-service:8080;
    }

    upstream auth_service {
        server auth-service:8081;
    }

    server {
        listen 9090;

        location /feature-flag/ {
            proxy_pass http://ff_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /auth/api-gateway/internal/ {
            return 404;
        }

        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }



        location / {
            return 404;
        }
    }
}
