services:
  postgres:
    image: postgres:18-alpine
    container_name: ff-service-postgres
    environment:
      POSTGRES_DB: ff-service
      POSTGRES_USER: ff-service
      POSTGRES_PASSWORD: ff-service
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC+3
    ports:
      - "5432:5432"
    volumes:
      - ff_service_pgdata:/var/lib/postgresql/data/pgdata
    shm_size: "256m"
    restart: unless-stopped


volumes:
  ff_service_pgdata:
    name: ff_service_pgdata