micronaut:
  application:
    name: feature-flag-service
  router:
    static-resources:
      swagger:
        enabled: true
        mapping: /swagger/**
        paths: classpath:META-INF/swagger
      swagger-ui:
        enabled: true
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/ff-service
    username: ff-service
    password: ff-service
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

liquibase:
  datasources:
    default:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml


