services:
  postgres-auth:
    image: postgres:latest
    container_name: authdatabase
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_DB}
      POSTGRES_USER: ${AUTH_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_DB_PASSWORD}
    volumes:
      - postgres-auth-data:/var/lib/postgresql

  redis-auth:
    image: redis:7-alpine
    container_name: authredis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    # Команда для включения сохранения данных на диск
    command: redis-server --appendonly yes

volumes:
  postgres-auth-data:
  redis-data: